@php
    // Initialize variables with defaults to avoid undefined variable errors
    $uniqueId = $uniqueId ?? 'field-' . uniqid();
    $wirePath = $wirePath ?? ($key ?? 'unknown');
    $categoryOptions = $categoryOptions ?? [];
    
    $label = $label ?? \Illuminate\Support\Str::headline($key ?? 'field');
    $isArray = is_array($value);
    $isAssoc = $isArray && array_values($value) !== $value;
    $isList = $isArray && !$isAssoc;
    $isScalarList = $isList && (empty($value) || !is_array($value[0] ?? null));
    
    // Check for field configuration from _field_config
    $fieldConfig = [];
    if (isset($GLOBALS['_field_config']) && isset($key) && isset($GLOBALS['_field_config'][$key])) {
        $fieldConfig = $GLOBALS['_field_config'][$key];
    }
    
    // Get field properties from config or auto-detect
    $fieldType = $fieldConfig['type'] ?? null;
    $label = $fieldConfig['label'] ?? $label;
    $placeholder = $fieldConfig['placeholder'] ?? '';
    $helpText = $fieldConfig['help'] ?? '';
    $isRequired = $fieldConfig['required'] ?? true;
    $maxLength = $fieldConfig['maxLength'] ?? null;
    $showCounter = $fieldConfig['showCounter'] ?? false;
    $rows = $fieldConfig['rows'] ?? 3;
    
    // Enhanced image detection: check key name OR value content OR explicit type
    $isImageKey = $fieldType === 'image' || false;
    if (!$isImageKey && is_string($key)) {
        // Check if key name suggests it's an image
        $isImageKey = preg_match('/(image|logo|banner|profile|photo|avatar|icon|bg|thumb|background)/i', $key);
        
        // Also check if value looks like an image URL
        if (!$isImageKey && is_string($value)) {
            $isImageKey = preg_match('/(\.jpg|\.jpeg|\.png|\.gif|\.webp|\.svg)/i', $value) || 
                          preg_match('/url\([\'"]?https?:\/\//i', $value);
        }
    }
    
    $isTextArea = $fieldType === 'textarea' || (is_string($key) && preg_match('/(description|desc|about|bio|note|tagline|address|subtitle|message)/i', $key));
    $isUrl = $fieldType === 'url' || (is_string($key) && preg_match('/(url|link|website|maps|facebook|instagram|youtube|twitter|whatsapp)/i', $key) && !$isImageKey);
    $isPhone = $fieldType === 'tel' || (is_string($key) && preg_match('/(phone|mobile|whatsapp|tel)/i', $key));
    $isNumber = $fieldType === 'number' || (is_string($key) && preg_match('/(price|old_price|oldprice|amount|qty|quantity|total)/i', $key));
    $isDate = $fieldType === 'date';
    $isTime = $fieldType === 'time';
    $isDateTime = $fieldType === 'datetime';
    $isCategoryKey = $fieldType === 'select' || (is_string($key) && preg_match('/^(category_key|cat)$/i', $key));
    $isToggle = $fieldType === 'toggle' || $fieldType === 'boolean';
    
    // Detect auto-generated files that should not be editable (QR code and vCard)
    $isAutoGeneratedFile = is_string($key) && (strtolower($key) === 'qr' || strtolower($key) === 'vcard');

    $uploadPath = 'uploads.' . $wirePath;
    $wrapperClass = ($isAssoc || $isList || $isScalarList) ? 'col-12' : 'col-lg-6';
    
    // Ensure unique ID is always set
    $uniqueId = 'field-' . str_replace(['.', '[', ']'], '-', $wirePath) . '-' . uniqid();
@endphp

@if ($isAssoc)
    <div class="col-12 mb-4">
        <div class="border rounded-3 p-3" style="background-color: #f8fafc;">
            <div class="fw-semibold mb-3 d-flex align-items-center">
                <i class="mdi mdi-folder-outline me-2 text-primary"></i>
                {{ $label }}
            </div>
            <div class="row">
                @foreach ($value as $childKey => $childValue)
                    @include('livewire.vcards.partials.field', [
                        'key' => $childKey,
                        'value' => $childValue,
                        'wirePath' => $wirePath . '.' . $childKey,
                        'categoryOptions' => $categoryOptions,
                        'uniqueId' => 'field-' . str_replace(['.', '[', ']'], '-', $wirePath . '.' . $childKey) . '-' . uniqid(),
                    ])
                @endforeach
            </div>
        </div>
    </div>
@elseif ($isScalarList)
    <div class="col-12 mb-4">
        <label class="form-label fw-semibold">{{ $label }}</label>
        <div class="d-flex flex-column gap-2">
            @foreach ($value as $i => $item)
                <div class="d-flex gap-2 align-items-center" wire:key="{{ $wirePath }}-{{ $i }}">
                    <input type="text" class="form-control" wire:model="form.{{ $wirePath }}.{{ $i }}">
                    <button type="button" class="btn btn-outline-secondary btn-sm rounded-circle p-0" style="width: 32px; height: 32px;" wire:click="moveRow('{{ $wirePath }}', {{ $i }}, -1)" title="Move Up">
                        <i class="mdi mdi-arrow-up"></i>
                    </button>
                    <button type="button" class="btn btn-outline-secondary btn-sm rounded-circle p-0" style="width: 32px; height: 32px;" wire:click="moveRow('{{ $wirePath }}', {{ $i }}, 1)" title="Move Down">
                        <i class="mdi mdi-arrow-down"></i>
                    </button>
                    <button type="button" class="btn btn-outline-danger btn-sm rounded-circle p-0" style="width: 32px; height: 32px;" wire:click="confirmRemoveRow('{{ $wirePath }}', {{ $i }})" title="Remove">
                        <i class="mdi mdi-delete"></i>
                    </button>
                </div>
            @endforeach
        </div>
        <button type="button" class="btn btn-sm btn-primary mt-2" wire:click="addRow('{{ $wirePath }}')">
            <i class="mdi mdi-plus"></i> Add Item
        </button>
    </div>
@elseif ($isList)
    @php
        $columns = array_keys($value[0] ?? []);
        $itemLabel = \Illuminate\Support\Str::singular($label);
        
        // Detect image columns (exclude background color fields like thumbBg, tagBg)
        $imageColumns = array_filter($columns, function($col) {
            // Exclude fields ending with Bg or _bg (these are color fields, not images)
            if (preg_match('/(Bg|_bg)$/i', $col)) return false;
            return preg_match('/(image|logo|banner|profile|photo|avatar|icon|thumb|picture)/i', $col);
        });
        
        // Filter out tag, color, and background columns
        $excludeColumns = array_filter($columns, function($col) {
            return preg_match('/(tag|color|Bg|_bg|id)/i', $col);
        });
        
        // Get other columns (excluding images and excluded columns)
        $otherColumns = array_diff($columns, $imageColumns, $excludeColumns);
        
        // Display columns with images first, then others
        $displayColumns = array_merge($imageColumns, $otherColumns);
    @endphp
    
    <div class="col-12 mb-4">
        <!-- Header Section -->
        @if (!($hideListHeaderButton ?? false))
            <div class="d-flex justify-content-end align-items-center mb-3 pb-3 border-bottom">
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addModal{{ $wirePath }}">
                    <i class="mdi mdi-plus me-1"></i> Add {{ $itemLabel }}
                </button>
            </div>
        @endif

        @if (empty($value))
            <!-- Empty State -->
            <div class="text-center py-5" style="background: linear-gradient(135deg, #f8fafc 0%, #f1f5f9 100%); border-radius: 12px; border: 2px dashed #cbd5e1;">
                <div class="mb-3">
                    <i class="mdi mdi-table-outline" style="font-size: 48px; color: #94a3b8;"></i>
                </div>
                <p class="fw-semibold text-muted mb-2">No {{ strtolower($label) }} Added</p>
                <p class="text-muted small mb-3">Start by adding your first {{ strtolower($itemLabel) }}</p>
                <button type="button" class="btn btn-sm btn-primary" data-bs-toggle="modal" data-bs-target="#addModal{{ $wirePath }}">
                    <i class="mdi mdi-plus"></i> Add First {{ $itemLabel }}
                </button>
            </div>
        @else
            <!-- Table -->
            <div class="table-responsive" style="border-radius: 12px; border: 1px solid #e2e8f0; overflow: hidden;">
                <table class="table table-hover align-middle mb-0">
                    <thead style="background-color: #f8fafc; border-bottom: 2px solid #e2e8f0;">
                        <tr>
                            <th style="width: 40px; font-weight: 600; color: #475569; font-size: 0.85rem; padding: 12px 8px; text-align: center;">
                                <i class="mdi mdi-drag-vertical" style="opacity: 0.5;"></i>
                            </th>
                            @foreach ($displayColumns as $col)
                                @php
                                    $isImage = in_array($col, $imageColumns);
                                    $colLabel = $isImage ? 'Image' : \Illuminate\Support\Str::headline($col);
                                    $isColTextarea = preg_match('/(description|desc|about|bio|note|details|content)/i', $col);
                                @endphp
                                <th style="font-weight: 600; color: #475569; font-size: 0.85rem; padding: 12px 16px; min-width: {{ $isColTextarea ? '150px' : '120px' }};">
                                    {{ $colLabel }}
                                </th>
                            @endforeach
                            <th style="width: 120px; font-weight: 600; color: #475569; font-size: 0.85rem; padding: 12px 16px; text-align: center;">
                                Actions
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($value as $i => $row)
                            @php
                                $displayTitle = "Item #" . ($i + 1);
                                $namePriority = ['name', 'title', 'product_name', 'service_name', 'category_name', 'item_name', 'label', 'brand'];
                                
                                foreach ($namePriority as $nameField) {
                                    if (isset($row[$nameField]) && is_string($row[$nameField]) && !empty(trim($row[$nameField]))) {
                                        $displayTitle = trim($row[$nameField]);
                                        break;
                                    }
                                }
                            @endphp
                            <tr wire:key="{{ $wirePath }}-{{ $i }}" 
                                class="sortable-row" 
                                data-row-index="{{ $i }}"
                                style="border-bottom: 1px solid #e2e8f0; cursor: move;">
                                <td style="padding: 12px 8px; text-align: center; cursor: grab;" class="drag-handle">
                                    <i class="mdi mdi-drag-vertical text-muted"></i>
                                </td>
                                @foreach ($displayColumns as $col)
                                    @php
                                        $colValue = $row[$col] ?? '';
                                        $isColTextarea = preg_match('/(description|desc|about|bio|note|details|content)/i', $col);
                                        $isColImage = preg_match('/(image|logo|banner|profile|photo|avatar|icon|bg|thumb|picture)/i', $col) || 
                                                      (is_string($colValue) && (preg_match('/(\.jpg|\.jpeg|\.png|\.gif|\.webp|\.svg)/i', $colValue) || 
                                                       preg_match('/url\([\'"]?https?:\/\//i', $colValue)));
                                    @endphp
                                    <td style="padding: 12px 16px; max-width: 300px;">
                                        @if ($isColImage && !empty($colValue))
                                            @php
                                                $imageUrl = $colValue;
                                                if (preg_match('/url\([\'"]?(.*?)[\'"]?\)/i', $colValue, $matches)) {
                                                    $imageUrl = $matches[1];
                                                }
                                                if (isset($assetBaseUrl) && is_string($imageUrl) && !preg_match('~^(https?:)?//|data:|/~', $imageUrl)) {
                                                    $imageUrl = rtrim($assetBaseUrl, '/') . '/' . ltrim($imageUrl, '/');
                                                }
                                            @endphp
                                            <img src="{{ $imageUrl }}" alt="{{ $col }}" style="width: 50px; height: 50px; object-fit: cover; border-radius: 6px; border: 1px solid #e2e8f0;">
                                        @else
                                            <span class="form-control-plaintext" style="font-size: 0.85rem;">
                                                @php
                                                    if (is_array($colValue)) {
                                                        echo 'Array (' . count($colValue) . ' items)';
                                                    } elseif (is_object($colValue)) {
                                                        echo 'Object';
                                                    } elseif (!empty($colValue)) {
                                                        echo is_string($colValue) && strlen($colValue) > 50 ? substr($colValue, 0, 50) . '...' : $colValue;
                                                    } else {
                                                        echo '—';
                                                    }
                                                @endphp
                                            </span>
                                        @endif
                                    </td>
                                @endforeach
                                <td style="padding: 12px 16px; text-align: center;">
                                    <div class="d-flex gap-1 justify-content-center">
                                        <!-- View/Edit Modal Button -->
                                        <button type="button" class="btn btn-sm btn-outline-info rounded-circle p-0" style="width: 32px; height: 32px;" data-bs-toggle="modal" data-bs-target="#editModal{{ $wirePath }}{{ $i }}" title="Edit All Fields">
                                            <i class="mdi mdi-pencil" style="font-size: 14px;"></i>
                                        </button>
                                        
                                        <!-- Move Up -->
                                        <button type="button" class="btn btn-sm btn-outline-secondary rounded-circle p-0" style="width: 32px; height: 32px;" wire:click.stop="moveRow('{{ $wirePath }}', {{ $i }}, -1)" title="Move Up" {{ $i === 0 ? 'disabled' : '' }}>
                                            <i class="mdi mdi-arrow-up" style="font-size: 14px;"></i>
                                        </button>
                                        
                                        <!-- Move Down -->
                                        <button type="button" class="btn btn-sm btn-outline-secondary rounded-circle p-0" style="width: 32px; height: 32px;" wire:click.stop="moveRow('{{ $wirePath }}', {{ $i }}, 1)" title="Move Down" {{ $i === count($value) - 1 ? 'disabled' : '' }}>
                                            <i class="mdi mdi-arrow-down" style="font-size: 14px;"></i>
                                        </button>
                                        
                                        <!-- Delete -->
                                        <button type="button" class="btn btn-sm btn-outline-danger rounded-circle p-0" style="width: 32px; height: 32px;" wire:click="confirmRemoveRow('{{ $wirePath }}', {{ $i }})" title="Delete">
                                            <i class="mdi mdi-delete" style="font-size: 14px;"></i>
                                        </button>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

            <!-- Edit Modal for each row -->
            @foreach ($value as $i => $row)
                @php
                    $displayTitle = "Item #" . ($i + 1);
                    $namePriority = ['name', 'title', 'product_name', 'service_name', 'category_name', 'item_name', 'label', 'brand'];
                    
                    foreach ($namePriority as $nameField) {
                        if (isset($row[$nameField]) && is_string($row[$nameField]) && !empty(trim($row[$nameField]))) {
                            $displayTitle = trim($row[$nameField]);
                            break;
                        }
                    }
                @endphp
                <div class="modal fade" id="editModal{{ $wirePath }}{{ $i }}" tabindex="-1" aria-labelledby="editLabel{{ $wirePath }}{{ $i }}" aria-hidden="true" wire:ignore.self>
                    <div class="modal-dialog modal-lg modal-dialog-scrollable">
                        <div class="modal-content">
                            <div class="modal-header" style="border-bottom: 1px solid #e2e8f0; background-color: #f8fafc;">
                                <h5 class="modal-title fw-semibold" id="editLabel{{ $wirePath }}{{ $i }}">
                                    <i class="mdi mdi-pencil me-2"></i>Edit {{ \Illuminate\Support\Str::limit($displayTitle, 35) }}
                                </h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body p-4">
                                <div class="row g-3">
                                    @foreach ($columns as $col)
                                        @php
                                            // Skip id, tag, color, and background fields
                                            if (preg_match('/(^id$|tag|color|Bg|_bg)/i', $col)) continue;
                                            
                                            $colValue = $row[$col] ?? '';
                                            // Detect image columns (exclude background color fields)
                                            $isColImage = !preg_match('/(Bg|_bg)$/i', $col) && (preg_match('/(image|logo|banner|profile|photo|avatar|icon|thumb|picture)/i', $col) || 
                                                          (is_string($colValue) && (preg_match('/(\.jpg|\.jpeg|\.png|\.gif|\.webp|\.svg)/i', $colValue) || 
                                                           preg_match('/url\([\'"]?https?:\/\//i', $colValue))));
                                            $isColTextarea = preg_match('/(description|desc|about|bio|note|details|content)/i', $col);
                                            $isColColor = preg_match('/(tag_color|color|bg_color|background_color)/i', $col);
                                            $isColNumber = preg_match('/(price|old_price|oldprice|amount|qty|quantity|total)/i', $col);
                                            $isColCategory = preg_match('/^(category_key|cat)$/i', $col);
                                            $modalModelPath = empty($wirePath) ? "form.{$i}.{$col}" : "form.{$wirePath}.{$i}.{$col}";
                                            $modalUploadPath = empty($wirePath) ? "uploads.{$i}.{$col}" : "uploads.{$wirePath}.{$i}.{$col}";
                                        @endphp
                                        
                                        <div class="col-12">
                                            <label class="form-label fw-semibold" style="font-size: 0.9rem;">
                                                {{ \Illuminate\Support\Str::headline($col) }}
                                            </label>
                                            @if ($isColImage)
                                                @php
                                                    // Check if this is an auto-generated file
                                                    $isAutoGenField = (strtolower($col) === 'qr' || strtolower($col) === 'vcard');
                                                    $fieldFileType = strtolower($col) === 'qr' ? 'QR Code' : 'vCard file';
                                                @endphp
                                                @if (!empty($colValue))
                                                    @php
                                                        $imageUrl = $colValue;
                                                        if (preg_match('/url\([\'"]?(.*?)[\'"]?\)/i', $colValue, $matches)) {
                                                            $imageUrl = $matches[1];
                                                        }
                                                        if (isset($assetBaseUrl) && is_string($imageUrl) && !preg_match('~^(https?:)?//|data:|/~', $imageUrl)) {
                                                            $imageUrl = rtrim($assetBaseUrl, '/') . '/' . ltrim($imageUrl, '/');
                                                        }
                                                    @endphp
                                                    <div class="mb-2">
                                                        <img src="{{ $imageUrl }}" alt="" style="max-width: 100%; max-height: 150px; border-radius: 8px; border: 1px solid #e2e8f0;">
                                                    </div>
                                                @endif
                                                @if ($isAutoGenField)
                                                    <div class="alert alert-info mb-0" style="font-size: 0.875rem;">
                                                        <i class="mdi mdi-information-outline me-1"></i>
                                                        {{ $fieldFileType }} is auto-generated and cannot be changed.
                                                    </div>
                                                @else
                                                    <div wire:loading wire:target="uploads.{{ empty($wirePath) ? $i : $wirePath . '.' . $i }}.{{ $col }}" class="mb-2">
                                                        <div class="spinner-border spinner-border-sm text-primary" role="status">
                                                            <span class="visually-hidden">Uploading...</span>
                                                        </div>
                                                        <small class="text-primary ms-2">Uploading image...</small>
                                                    </div>
                                                    <input type="file" class="form-control" wire:model.live="{{ $modalUploadPath }}" accept="image/*">
                                                    <small class="text-muted d-block mt-1">Upload image (JPG, PNG, GIF)</small>
                                                @endif
                                            @elseif ($isColCategory && !empty($categoryOptions))
                                                <select class="form-select" wire:model="{{ $modalModelPath }}">
                                                    <option value="" disabled>Select category</option>
                                                    @foreach ($categoryOptions as $option)
                                                        <option value="{{ $option['key'] }}">{{ $option['label'] }}</option>
                                                    @endforeach
                                                </select>
                                            @elseif ($isColColor)
                                                <div class="d-flex gap-2 align-items-center">
                                                    <input type="color" class="form-control form-control-color" wire:model="{{ $modalModelPath }}" style="width: 60px; height: 38px;" required>
                                                    <input type="text" class="form-control" wire:model="{{ $modalModelPath }}" placeholder="#000000" required>
                                                </div>
                                            @elseif ($isColTextarea)
                                                <textarea class="form-control" rows="4" wire:model="{{ $modalModelPath }}" required></textarea>
                                            @else
                                                <input type="{{ $isColNumber ? 'number' : 'text' }}" class="form-control" wire:model="{{ $modalModelPath }}" {{ $isColNumber ? 'step=0.01' : '' }} required>
                                            @endif
                                        </div>
                                    @endforeach
                                </div>
                            </div>
                            <div class="modal-footer" style="border-top: 1px solid #e2e8f0;">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" wire:loading.attr="disabled">Close</button>
                                <button type="button" class="btn btn-primary" wire:click="saveAndNotify" wire:loading.attr="disabled">
                                    <span wire:loading.remove>
                                        <i class="mdi mdi-check me-1"></i>Save Changes
                                    </span>
                                    <span wire:loading>
                                        <span class="spinner-border spinner-border-sm me-1" role="status"></span>
                                        Saving...
                                    </span>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
        @endif

        <!-- Add New Item Modal -->
        <div class="modal fade" id="addModal{{ $wirePath }}" tabindex="-1" aria-labelledby="addLabel{{ $wirePath }}" aria-hidden="true" wire:ignore.self>
            <div class="modal-dialog modal-lg modal-dialog-scrollable">
                <div class="modal-content">
                    <div class="modal-header" style="border-bottom: 1px solid #e2e8f0; background-color: #f8fafc;">
                        <h5 class="modal-title fw-semibold" id="addLabel{{ $wirePath }}">
                            <i class="mdi mdi-plus-circle me-2"></i>Add New {{ $itemLabel }}
                        </h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body p-4">
                        <div class="row g-3">
                            @foreach ($columns as $col)
                                @php
                                    // Skip id, tag, color, and background fields
                                    if (preg_match('/(^id$|tag|color|Bg|_bg)/i', $col)) continue;
                                    
                                    // Detect image columns (exclude background color fields)
                                    $isColImage = !preg_match('/(Bg|_bg)$/i', $col) && preg_match('/(image|logo|banner|profile|photo|avatar|icon|thumb|picture)/i', $col);
                                    $isColTextarea = preg_match('/(description|desc|about|bio|note|details|content)/i', $col);
                                    $isColColor = preg_match('/(tag_color|color|bg_color|background_color)/i', $col);
                                    $isColNumber = preg_match('/(price|old_price|oldprice|amount|qty|quantity|total)/i', $col);
                                    $isColCategory = preg_match('/^(category_key|cat)$/i', $col);
                                @endphp
                                
                                <div class="col-12">
                                    <label class="form-label fw-semibold" style="font-size: 0.9rem;">
                                        {{ \Illuminate\Support\Str::headline($col) }}
                                    </label>
                                    @if ($isColImage)
                                        @php
                                            // Check if this is an auto-generated file
                                            $isAutoGenField = (strtolower($col) === 'qr' || strtolower($col) === 'vcard');
                                            $fieldFileType = strtolower($col) === 'qr' ? 'QR Code' : 'vCard file';
                                        @endphp
                                        @if ($isAutoGenField)
                                            <div class="alert alert-info mb-0" style="font-size: 0.875rem;">
                                                <i class="mdi mdi-information-outline me-1"></i>
                                                {{ $fieldFileType }} is auto-generated and cannot be changed.
                                            </div>
                                        @else
                                            <div wire:loading wire:target="uploads.newItem.{{ $col }}" class="mb-2">
                                                <div class="spinner-border spinner-border-sm text-primary" role="status">
                                                    <span class="visually-hidden">Uploading...</span>
                                                </div>
                                                <small class="text-primary ms-2">Uploading image...</small>
                                            </div>
                                            <input type="file" class="form-control" wire:model.live="uploads.newItem.{{ $col }}" accept="image/*">
                                            <small class="text-muted d-block mt-1">Upload image (JPG, PNG, GIF)</small>
                                        @endif
                                    @elseif ($isColCategory && !empty($categoryOptions))
                                        <select class="form-select" wire:model="newItem.{{ $col }}">
                                            <option value="" disabled>Select category</option>
                                            @foreach ($categoryOptions as $option)
                                                <option value="{{ $option['key'] }}">{{ $option['label'] }}</option>
                                            @endforeach
                                        </select>
                                    @elseif ($isColColor)
                                        <div class="d-flex gap-2 align-items-center">
                                            <input type="color" class="form-control form-control-color" wire:model="newItem.{{ $col }}" style="width: 60px; height: 38px;" required>
                                            <input type="text" class="form-control" wire:model="newItem.{{ $col }}" placeholder="#000000" required>
                                        </div>
                                    @elseif ($isColTextarea)
                                        <textarea class="form-control" rows="4" wire:model="newItem.{{ $col }}" required></textarea>
                                    @else
                                        <input type="{{ $isColNumber ? 'number' : 'text' }}" class="form-control" wire:model="newItem.{{ $col }}" {{ $isColNumber ? 'step=0.01' : '' }} required>
                                    @endif
                                </div>
                            @endforeach
                        </div>
                    </div>
                    <div class="modal-footer" style="border-top: 1px solid #e2e8f0;">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" wire:loading.attr="disabled">Cancel</button>
                        <button type="button" class="btn btn-primary" wire:click="addRowAndSave('{{ $wirePath }}', @js($columns))" wire:loading.attr="disabled">
                            <span wire:loading.remove>
                                <i class="mdi mdi-check me-1"></i>Add {{ $itemLabel }}
                            </span>
                            <span wire:loading>
                                <span class="spinner-border spinner-border-sm me-1" role="status"></span>
                                Adding...
                            </span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
@else
    <div class="{{ $wrapperClass }} mb-3">
        <label class="form-label fw-semibold" for="{{ $uniqueId }}">
            {{ $label }}
            @if ($helpText)
                <i class="mdi mdi-help-circle-outline text-muted ms-1" 
                   data-bs-toggle="tooltip" 
                   data-bs-placement="top" 
                   title="{{ $helpText }}"
                   style="cursor: help; font-size: 0.9rem;"></i>
            @endif
        </label>
        @if ($isToggle)
            <div class="form-check form-switch">
                <input class="form-check-input" 
                       type="checkbox" 
                       id="{{ $uniqueId }}"
                       wire:model="form.{{ $wirePath }}"
                       style="cursor: pointer;">
                <label class="form-check-label" for="{{ $uniqueId }}">{{ $placeholder ?: 'Enable' }}</label>
            </div>
        @elseif ($isDate || $isTime || $isDateTime)
            <input type="text" 
                   id="{{ $uniqueId }}"
                   class="form-control flatpickr-input"
                   wire:model="form.{{ $wirePath }}"
                   placeholder="{{ $placeholder }}"
                   data-field-type="{{ $isDate ? 'date' : ($isTime ? 'time' : 'datetime') }}"
                   {{ $isRequired ? 'required' : '' }}>
            @if ($helpText)
                <small class="form-text text-muted d-block mt-1">
                    <i class="mdi mdi-information-outline"></i> {{ $helpText }}
                </small>
            @endif
        @elseif ($isAutoGeneratedFile)
            @php
                $fileType = strtolower($key) === 'qr' ? 'QR Code' : 'vCard file';
            @endphp
            @if (!empty($value))
                <div class="mb-2 p-2 bg-light border rounded">
                    <i class="mdi mdi-file-outline me-1"></i>
                    <span class="text-muted">{{ $value }}</span>
                </div>
            @endif
            <div class="alert alert-info mb-0" style="font-size: 0.875rem;">
                <i class="mdi mdi-information-outline me-1"></i>
                {{ $fileType }} is auto-generated and cannot be changed manually.
            </div>
        @elseif ($isImageKey)
            @if (!empty($value))
                @php
                    // Extract URL from url('...') wrapper if present
                    $imageUrl = $value;
                    if (preg_match('/url\([\'"]?(.*?)[\'"]?\)/i', $value, $matches)) {
                        $imageUrl = $matches[1];
                    }
                    if (isset($assetBaseUrl) && is_string($imageUrl) && !preg_match('~^(https?:)?//|data:|/~', $imageUrl)) {
                        $imageUrl = rtrim($assetBaseUrl, '/') . '/' . ltrim($imageUrl, '/');
                    }
                @endphp
                <div class="mb-2">
                    <img src="{{ $imageUrl }}" alt="" style="max-width: 160px; height: auto;" class="img-thumbnail">
                </div>
            @endif
            <input type="file" class="form-control" wire:model.live="{{ $uploadPath }}" accept="image/*">
            <small class="form-text text-muted d-block mt-1">
                <i class="mdi mdi-information-outline"></i> Upload a new image to replace the current one
            </small>
        @elseif ($isCategoryKey && !empty($categoryOptions))
            <select class="form-select" 
                    id="{{ $uniqueId }}"
                    wire:model="form.{{ $wirePath }}"
                    {{ $isRequired ? 'required' : '' }}>
                <option value="">{{ $placeholder ?: 'Select category' }}</option>
                @foreach ($categoryOptions as $option)
                    <option value="{{ $option['key'] }}">{{ $option['label'] }}</option>
                @endforeach
            </select>
            @if ($helpText)
                <small class="form-text text-muted d-block mt-1">
                    <i class="mdi mdi-information-outline"></i> {{ $helpText }}
                </small>
            @endif
        @elseif ($isTextArea)
            <textarea class="form-control" 
                      id="{{ $uniqueId }}"
                      rows="{{ $rows }}" 
                      wire:model="form.{{ $wirePath }}"
                      placeholder="{{ $placeholder }}"
                      {{ $maxLength ? "maxlength={$maxLength}" : '' }}
                      {{ $isRequired ? 'required' : '' }}
                      @if($showCounter && $maxLength) x-data="{ length: $wire.entangle('form.{{ $wirePath }}').live.length }" @endif></textarea>
            @if ($showCounter && $maxLength)
                <small class="form-text text-muted d-block mt-1" x-text="length + ' / {{ $maxLength }} characters'"></small>
            @elseif ($helpText)
                <small class="form-text text-muted d-block mt-1">
                    <i class="mdi mdi-information-outline"></i> {{ $helpText }}
                </small>
            @endif
        @else
            <input type="{{ $isNumber ? 'number' : ($isUrl ? 'url' : ($isPhone ? 'tel' : 'text')) }}" 
                   id="{{ $uniqueId }}"
                   class="form-control" 
                   wire:model="form.{{ $wirePath }}"
                   placeholder="{{ $placeholder }}"
                   {{ $isNumber ? 'step=0.01' : '' }}
                   {{ $maxLength && !$isNumber ? "maxlength={$maxLength}" : '' }}
                   {{ $isRequired ? 'required' : '' }}>
            @if ($helpText)
                <small class="form-text text-muted d-block mt-1">
                    <i class="mdi mdi-information-outline"></i> {{ $helpText }}
                </small>
            @endif
        @endif
    </div>
@endif

@once
@push('scripts')
<script src="https://cdn.jsdelivr.net/npm/flatpickr@4.6.13/dist/flatpickr.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr@4.6.13/dist/flatpickr.min.css">
<script src="https://cdn.jsdelivr.net/npm/sortablejs@1.15.0/Sortable.min.js"></script>
<script>
document.addEventListener('DOMContentLoaded', function() {
    // Initialize Flatpickr for date/time fields
    function initFlatpickr() {
        document.querySelectorAll('.flatpickr-input').forEach(input => {
            if (input._flatpickr) return;
            
            const fieldType = input.dataset.fieldType;
            const config = {
                altInput: true,
                allowInput: true,
                onChange: function(selectedDates, dateStr) {
                    input.dispatchEvent(new Event('input', { bubbles: true }));
                }
            };
            
            if (fieldType === 'date') {
                config.dateFormat = 'Y-m-d';
                config.altFormat = 'F j, Y';
            } else if (fieldType === 'time') {
                config.enableTime = true;
                config.noCalendar = true;
                config.dateFormat = 'H:i';
                config.time_24hr = true;
            } else if (fieldType === 'datetime') {
                config.enableTime = true;
                config.dateFormat = 'Y-m-d H:i';
                config.altFormat = 'F j, Y at h:i K';
            }
            
            flatpickr(input, config);
        });
    }
    
    // Initialize Bootstrap tooltips
    function initTooltips() {
        const tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle=\"tooltip\"]'));
        tooltipTriggerList.forEach(function (tooltipTriggerEl) {
            if (!bootstrap.Tooltip.getInstance(tooltipTriggerEl)) {
                new bootstrap.Tooltip(tooltipTriggerEl);
            }
        });
    }
    
    // Initialize all
    initFlatpickr();
    initTooltips();
    
    // Reinitialize after Livewire updates
    if (typeof Livewire !== 'undefined') {
        Livewire.hook('message.processed', () => {
            setTimeout(() => {
                initFlatpickr();
                initTooltips();
            }, 100);
        });
    }
});
</script>
<style>
.sortable-ghost {
    opacity: 0.4;
    background: #f1f5f9 !important;
}
.sortable-drag {
    opacity: 0.8;
    box-shadow: 0 5px 15px rgba(0,0,0,0.2);
}
.drag-handle:active {
    cursor: grabbing !important;
}
</style>
@endpush
@endonce
